#' Read a dlf file (Daisy log file) or a directory of dlf files
#'
#' @param path Path to dlf file or directory containing dlf files.
#' @param mode One of 'auto', 'file', 'spawn', 'dir. Default is 'auto'.
#' If 'auto' try to guess the mode.
#' If 'file' assume path is a single dlf file.
#' If 'spawn' assume path is a directory containing log directories generated by
#' the daisy spawn program.
#' If 'dir' assume path is a directory tree containing dlf files
#' @param pattern Regex pattern of files to include. Only relevant for modes
#' 'auto', 'spawn', and 'dir'
#' @param col_name Name of column to store directory name in. Only relevant for
#' modes 'auto' and 'spawn'.
#' @param convert_time If TRUE convert daisy time to a timestamp stored under
#' column 'time' in the data slot of each dlf
#' @param convert_depth If TRUE and the file contains depth data, convert it to
#' a nicer depth format with three columns (depth, time, variable). It implies
#' convert_time=TRUE
#'
#' @return For mode 'file': An S4 object of class Dlf with three slots: header,
#' units, data.
#' header is list with everything in the dlf file before the data. key: value
#' pairs from the header are stored as named components of the list.
#' units is a data.frame containing the units of the values in data.
#' data is a data.frame containing the logged values
#'
#' For mode 'spawn': A named list of Dlf objects, where names are names of log
#' types
#' For mode 'dir': A named list of Dlf objects, where names are paths to each
#' file.
#'
#' @seealso read_dlf_file, read_dlf_dir, read_dlf_spawn
#'
#' @export
#'
#' @examples
#' data_dir <- system.file("extdata", package="daisyrVis")
#' path <- file.path(data_dir, "annual/Annual-FN/HourlyP-Annual-FN-2-2b.dlf")
#' dlf <- read_dlf(path)
#' slotNames(dlf)
#' names(dlf@header)
#' dlf@units$Crop
#' dlf$Crop # equivalent to dlf@data$Crop
#' dlf[["Crop"]]
read_dlf <- function(path, mode="auto", pattern=".*\\.dlf", col_name="sim",
                     convert_time=TRUE, convert_depth=TRUE) {
    if (mode == "auto") {
        mode <- guess_read_mode(path, pattern)
    }
    if (mode == "file") {
        dlfs <- daisyrVis::read_dlf_file(path)
    } else if (mode == "spawn") {
        dlfs <- daisyrVis::read_dlf_spawn(path, pattern, col_name)
    } else if (mode == "dir") {
        dlfs <- daisyrVis::read_dlf_dir(path, pattern)
    } else {
        stop(paste("Unknown mode", mode))
    }
    if (convert_time) {
        dlfs <- daisyrVis::daisy_time_to_timestamp(dlfs)
        if (convert_depth) {
            unlist <- FALSE
            if (!is.list(dlfs)) {
                unlist <- TRUE
                dlfs <- list(dlfs)
            }
            dlfs <- lapply(dlfs, function(dlf) {
                if (is_depth_data(dlf, col_name)) {
                    var_name <- guess_var_name(dlf, col_name)
                    daisyrVis::depth_wide_to_long(dlf, var_name)
                } else {
                    dlf
                }
            })
            if (unlist) {
                dlfs <- dlfs[[1]]
            }
        }
    } else if (convert_depth) {
        message("Cannot convert depth is not converted")
    }
    dlfs
}


guess_read_mode <- function(path, pattern) {
    mode <- "auto"
    info <- file.info(path)
    if (!info$isdir) {
        mode <- "file"
    } else {
        ## Try to see if is matches what we expect from spawn
        ## So there should be a set of directories, each containing the same
        ## file matching pattern
        dirs <- list.dirs(path)
        if (length(dirs) == 1) {
            if (length(list.files(path, pattern=pattern, recursive=TRUE)) > 0) {
                ## If there is only a base dir with files we use 'dir' mode
                mode <- "dir"
            } else {
                stop(paste0("path '", path, "' is a directory but does",
                            " contain any files matching pattern", pattern))
            }
        } else {
            # Try to see if we can read it as spawn output
            file_names <- c()
            for (dir in dirs) {
                if (dir == path) {
                    if (length(list.files(dir, pattern=pattern)) > 0) {
                        ## Don't know what to do when there are dlf files in the
                        # basedir
                        mode <- "dir"
                        break
                    }
                    ## Basedir is empty. Skip it and check if files are the same
                    ## in the other dirs
                    next
                }
                if (is.null(file_names)) {
                    ## This is the first dir we process
                    file_names <- list.files(dir, pattern=pattern,
                                             recursive=TRUE)
                } else {
                    other_file_names <- list.files(dir, pattern=pattern,
                                                   recursive=TRUE)
                    if (!setequal(file_names, other_file_names)) {
                        ## If the set of files is not the same for all
                        ## directories we use 'dir' mode
                        mode <- "dir"
                        break
                    }
                }
            }
            if (mode == "auto") {
                ## If we did not set to "dir" in the loop, it is "spawn"
                mode <- "spawn"
            }
        }
    }
    mode
}

is_depth_data <- function(dlf, col_name) {
    columns <- colnames(dlf@data)
    columns <- columns[!(columns %in% c('year', 'month', 'day', 'mday', 'hour',
                                        col_name, 'time'))]
    all(grepl("..AT..", columns, fixed=TRUE))
}

guess_var_name <- function(dlf, col_name) {
    columns <- colnames(dlf@data)
    columns <- columns[!(columns %in% c('year', 'month', 'day', 'mday', 'hour',
                                        col_name, 'time'))]
    strsplit(columns[1], '..AT..', fixed=TRUE)[[1]][1]
}
